# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'

    - name: Build
      run: GOOS=windows GOARCH=amd64 go build -o ./valcord.exe -v .

    - name: Test
      run: GOOS=windows GOARCH=amd64 go build -o ./valcord.exe -v .
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Valcord
        path: ./valcord.exe

    - name: Create GitHub Release and Upload Binary
      uses: softprops/action-gh-release@v2
      with:
        name: "vaclord V- ${{ github.sha }}"
        tag_name: "release-run-${{ github.sha }}"
        files: ./valcord.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
