name: Go Release Build

on:
  push:
    tags:
      - 'v*'  # Trigger only when a version tag like v1.0.0 is pushed

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'

    - name: Build for Windows
      run: GOOS=windows GOARCH=amd64 go build -o valcord.exe -v .
    
    - name: Test
      run: GOOS=windows GOARCH=amd64 go build -o ./valcord.exe -v .

    - name: Strip 'v' from tag
      id: version
      run: echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

    - name: Upload Build Artifact to Release
      uses: softprops/action-gh-release@v2
      with:
        name: "Valcord ${{ steps.version.outputs.version }}"
        tag_name: ${{ github.ref_name }}
        files: ./valcord.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
