name: Go Release Build

on:
  push:
    tags:
      - 'v*'  # Trigger only when a version tag like v1.0.0 is pushed

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'

    - name: Get Short SHA
      id: shortsha
      run: echo "sha_short=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT

    - name: Build for Windows
      run: GOOS=windows GOARCH=amd64 go build -ldflags "-X 'main.versionSHA=${{ steps.shortsha.outputs.sha_short }}' -X 'main.version=${{ github.ref_name }}' " -o valcord.exe -v .
    
    - name: Test
      run: GOOS=windows GOARCH=amd64 go build -o ./valcord.exe -v .

    - name: Upload Build Artifact to Release
      uses: softprops/action-gh-release@v2
      with:
        name: "Valcord ${{ github.ref_name }}"
        tag_name: ${{ github.ref_name }}
        files: ./valcord.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
